version: 2

models:
  - name: fact_orders
    description: "Fact table containing order details"
    columns:
      - name: order_id
        description: "The unique identifier for each order"
        tests:
          - unique
          - not_null

      - name: order_placed_at
        description: "Timestamp when the order was placed"
        tests:
          - not_null

      - name: order_rating
        description: "Rating given for the order"

      - name: vendor_id
        description: "Identifier for the vendor associated with the order"
        tests:
          - not_null

      - name: customer_id
        description: "Identifier for the customer who placed the order"
        tests:
          - not_null

      - name: item_sku
        description: "Stock keeping unit of the item in the order"
        tests:
          - not_null

      - name: item_price
        description: "Price at which the item is sold"
        tests:
          - not_null

      - name: item_quantity
        description: "Quantity of the item in the order"
        tests:
          - not_null

  - name: dim_vendors
    description: "Dimension table containing vendor details"
    columns:
      - name: vendor_id
        description: "Unique identifier for the vendor"
        tests:
          - unique
          - not_null

      - name: vendor_name
        description: "Name of the vendor"
        tests:
          - not_null

      - name: vendor_address
        description: "Address of the vendor"

      - name: vendor_vertical
        description: "Vertical or category the vendor belongs to"
        tests:
          - not_null

  - name: dim_customers
    description: "Dimension table containing customer details"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests:
          - unique
          - not_null

      - name: customer_registered_at
        description: "Timestamp when the customer registered"
        tests:
          - not_null

  - name: dim_products
    description: "Dimension table containing item details"
    columns:
      - name: item_sku
        description: "Stock keeping unit for the item"
        tests:
          - not_null
      
      - name: vendor_id
        description: "vendor id selling this item"
        tests:
          - not_null      

      - name: item_name
        description: "Name of the item"
        tests:
          - not_null
